// Run this to test out the NodeDog validator.
// The code on the page is just to show how NodeDog validator can be used.
// Express and Jade are not required to use NodeDog, are just used here for demonstration purposes

require('./validator');
var express = require('express');

var app = express.createServer();

app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.methodOverride());
	app.use(express.logger());
	app.use(express.static(__dirname + '/static'));
});

app.set('views', __dirname + '/views');
app.set('view engine', 'jade');


//important NodeDog validator code to create the validator and set up what keys it should validate,
// how it should each key name, and what it should return when a validation function fails

// the paramater being passed to the Validator constructor
// is the path to the validation_checks.js file containing the validation method definitions
validatorObject = new Validator(__dirname+'/static/javascript/validation_checks');

validatorObject.addVariableToValidate("name",["required"],["Name is required"]);
validatorObject.addVariableToValidate("year",["required","exactLength-4","isInt"],["Year is required","Year must be 4 integers long","Year must be an integer"]);
	  
app.get('/', function(req, httpResponse)
{    
    httpResponse.render('list', 
    {
        // pass the properties generated by the validator object to the client so the client version of NodeDog
        // knows how to validate the form
       locals: {validate_properties: validatorObject.getClientSideValidationProperties(), msg:null}
    });
});

app.get('/message/:msg', function(req, httpResponse)
{    
    httpResponse.render('list', 
    {
       // pass the properties generated by the validator object to the client so the client version of NodeDog
       // knows how to validate the form
       locals: {validate_properties: validatorObject.getClientSideValidationProperties(), message: req.params.msg}
    });
});

app.post('/', function(req, httpResponse)
{
	//validate server side using the validation object created previously
	msg = validatorObject.validate(req.body);
	
	if(msg == null)
	{
		msg = "All NodeDog validation passed!";
	}
	httpResponse.redirect('/message/'+encodeURIComponent(msg)+"/");
});

app.listen(4000);